### ISSUE TITLE
Tests fail under Cygwin Perl 5.22

### ISSUE THREAD

**Issue by vadz** [rjbs/Dist-Zilla#497]
Here is the end of `cpanm` log:
```
PERL_DL_NONLAZY=1 "/usr/bin/perl.exe" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t t/commands/*.t t/diagnostics/*.t t/plugins/*.t
# 
# Versions for all modules listed in MYMETA.json (including optional ones):
# 
# === Configure Requires ===
# 
#     Module                  Want    Have
#     ----------------------- ---- -------
#     ExtUtils::MakeMaker      any 7.04_01
#     File::ShareDir::Install 0.06    0.10
# 
# === Build Requires ===
# 
#     Module              Want    Have
#     ------------------- ---- -------
#     ExtUtils::MakeMaker  any 7.04_01
# 
# === Test Requires ===
# 
#     Module                    Want     Have
#     ------------------------ ----- --------
#     CPAN::Meta::Check        0.007    0.012
#     CPAN::Meta::Requirements 2.121    2.132
#     ExtUtils::MakeMaker        any  7.04_01
#     ExtUtils::Manifest        1.66     1.70
#     File::Spec                 any     3.56
#     Software::License::None    any 0.103010
#     Test::FailWarnings         any    0.008
#     Test::Fatal                any    0.014
#     Test::File::ShareDir       any 1.001001
#     Test::More                0.96 1.001014
#     lib                        any     0.63
#     utf8                       any     1.17
# 
# === Test Recommends ===
# 
#     Module         Want     Have
#     ---------- -------- --------
#     CPAN::Meta 2.120900 2.150001
# 
# === Runtime Requires ===
# 
#     Module                                         Want       Have
#     ------------------------------------------ -------- ----------
#     App::Cmd::Command::version                      any      0.328
#     App::Cmd::Setup                               0.309      0.328
#     App::Cmd::Tester                              0.306      0.328
#     App::Cmd::Tester::CaptureExternal               any      0.328
#     Archive::Tar                                    any       2.04
#     CPAN::Meta::Converter                      2.101550   2.150001
#     CPAN::Meta::Merge                               any   2.150001
#     CPAN::Meta::Prereqs                        2.120630   2.150001
#     CPAN::Meta::Requirements                      2.121      2.132
#     CPAN::Meta::Validator                      2.101550   2.150001
#     CPAN::Uploader                             0.103004   0.103010
#     Carp                                            any       1.36
#     Class::Load                                    0.17       0.23
#     Config::INI::Reader                             any      0.025
#     Config::MVP::Assembler                          any   2.200010
#     Config::MVP::Assembler::WithBundles        2.200010   2.200010
#     Config::MVP::Reader                        2.101540   2.200010
#     Config::MVP::Reader::Findable::ByExtension      any   2.200010
#     Config::MVP::Reader::Finder                     any   2.200010
#     Config::MVP::Reader::INI                          2   2.101463
#     Config::MVP::Section                       2.200009   2.200010
#     Data::Dumper                                    any      2.158
#     Data::Section                              0.200002   0.200006
#     DateTime                                       0.44       1.21
#     Digest::MD5                                     any       2.54
#     Encode                                          any       2.72
#     ExtUtils::Manifest                             1.66       1.70
#     File::Copy::Recursive                           any       0.38
#     File::Find::Rule                                any       0.33
#     File::HomeDir                                   any       1.00
#     File::Path                                      any       2.09
#     File::ShareDir                                  any      1.102
#     File::ShareDir::Install                        0.03       0.10
#     File::Spec                                      any       3.56
#     File::Temp                                      any     0.2304
#     File::pushd                                     any      1.009
#     JSON::MaybeXS                                   any   1.003005
#     List::MoreUtils                                 any      0.413
#     List::Util                                     1.33       1.42
#     Log::Dispatchouli                          1.102220      2.012
#     Mixin::Linewise::Readers                      0.100      0.108
#     Module::CoreList                                any 5.20150520
#     Moose                                          0.92     2.1603
#     Moose::Role                                     any     2.1603
#     Moose::Util::TypeConstraints                    any     2.1603
#     MooseX::LazyRequire                             any       0.11
#     MooseX::Role::Parameterized                    1.01       1.08
#     MooseX::SetOnce                                 any   0.200002
#     MooseX::Types                                   any       0.46
#     MooseX::Types::Moose                            any       0.46
#     MooseX::Types::Path::Class                      any       0.08
#     MooseX::Types::Perl                             any   0.101343
#     PPI::Document                                   any      1.220
#     Params::Util                                    any       1.07
#     Path::Class                                    0.22       0.35
#     Path::Tiny                                    0.052      0.072
#     Perl::PrereqScanner                           1.016      1.023
#     Perl::Version                                   any      1.013
#     Pod::Eventual                              0.091480   0.094001
#     Scalar::Util                                    any       1.42
#     Software::License                          0.101370   0.103010
#     Software::LicenseUtils                          any   0.103010
#     Storable                                        any       2.53
#     String::Formatter                          0.100680   0.102084
#     String::RewritePrefix                         0.005      0.007
#     Sub::Exporter                                   any      0.987
#     Sub::Exporter::ForMethods                       any   0.100052
#     Sub::Exporter::Util                             any      0.987
#     Term::Encoding                                  any       0.02
#     Term::ReadKey                                   any       2.33
#     Term::ReadLine                                  any       1.15
#     Term::UI                                        any       0.46
#     Test::Deep                                      any      0.117
#     Text::Glob                                     0.08       0.09
#     Text::Template                                  any       1.46
#     Try::Tiny                                       any       0.22
#     YAML::Tiny                                      any       1.69
#     autodie                                         any       2.26
#     namespace::autoclean                            any       0.27
#     parent                                          any      0.232
#     strict                                          any       1.09
#     version                                         any     0.9909
#     warnings                                        any       1.32
# 
# === Runtime Recommends ===
# 
#     Module                Want    Have
#     --------------------- ---- -------
#     Archive::Tar::Wrapper 0.15 missing
#     Term::ReadLine::Gnu    any    1.26
# 
# === Runtime Suggests ===
# 
#     Module  Want    Have
#     ------- ---- -------
#     PPI::XS  any missing
# 
t/00-report-prereqs.t ........ ok
t/commands/authordeps.t ...... ok
t/commands/listdeps.t ........ ok
t/compile.t .................. ok
t/diagnostics/main-module.t .. ok
t/diagnostics/plugin-fail.t .. ok
t/empty-abstract.t ........... ok
t/file-addedby.t ............. ok
t/file.t ..................... ok
t/load_config.t .............. ok
t/minter.t ................... ok
t/plugins/autolicense.t ...... ok
t/plugins/autoname.t ......... ok
t/plugins/autoprereqs.t ...... ok
t/plugins/autoversion.t ...... ok
t/plugins/confirmrelease.t ... ok
t/plugins/distmeta-merge.t ... ok
Cannot determine local time zone
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 2 just after 6.
t/plugins/distmeta.t ......... 
Dubious, test returned 2 (wstat 512, 0x200)
All 6 subtests passed 
t/plugins/encoding.t ......... ok
t/plugins/extratests.t ....... ok
t/plugins/fakerelease.t ...... ok
t/plugins/ffbyname.t ......... ok
t/plugins/filefinders.t ...... ok
t/plugins/filter-b.t ......... ok
t/plugins/gatherdir.t ........ ok
t/plugins/generatefile.t ..... ok
t/plugins/installdirs.t ...... ok
Cannot determine local time zone
    # Child (non-ASCII author) exited without calling finalize()

#   Failed test 'non-ASCII author'
#   at /usr/lib/perl5/vendor_perl/5.22/Test/Builder.pm line 279.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 2 just after 2.
t/plugins/license.t .......... 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 1/2 subtests 
t/plugins/makemaker.t ........ ok
t/plugins/manifest.t ......... ok
t/plugins/metanoindex.t ...... ok
t/plugins/metaresources.t .... ok
t/plugins/misctests.t ........ ok
t/plugins/modulebuild.t ...... ok
t/plugins/nextrelease.t ...... ok
t/plugins/pkgdist.t .......... ok
t/plugins/pkgversion.t ....... ok
t/plugins/podsyntaxtests.t ... ok
t/plugins/podversion.t ....... ok
t/plugins/prereqs.t .......... ok
t/plugins/prunes.t ........... ok
Cannot determine local time zone
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 2 just after 3.
t/plugins/readme.t ........... 
Dubious, test returned 2 (wstat 512, 0x200)
All 3 subtests passed 
t/plugins/release_status.t ... ok
t/plugins/testrelease.t ...... ok
t/plugins/uploadtocpan.t ..... ok
t/tester-demo.t .............. ok
t/tester-sort.t .............. ok
t/tester.t ................... ok
t/util.t ..................... ok
t/zzz-check-breaks.t ......... ok

Test Summary Report
-------------------
t/plugins/distmeta.t       (Wstat: 512 Tests: 6 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
t/plugins/license.t        (Wstat: 512 Tests: 2 Failed: 1)
  Failed test:  2
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
t/plugins/readme.t         (Wstat: 512 Tests: 3 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
Files=50, Tests=453, 72 wallclock secs ( 0.12 usr  0.23 sys + 51.83 cusr 19.30 csys = 71.48 CPU)
Result: FAIL
Failed 3/50 test programs. 1/453 subtests failed.
Makefile:1868: recipe for target 'test_dynamic' failed
make: *** [test_dynamic] Error 255
-> FAIL Installing Dist::Zilla failed.
```

**Comment by pink-mist** [comment]
I have the same failure when building on a Slackware Linux box with perl 5.22.0. If I set `TZ=CET` when building, it works fine.

**Comment by pink-mist** [comment]
This is the output of `t/00-report-prereqs.t`

    #
    # Versions for all modules listed in MYMETA.json (including optional ones):
    #
    # === Configure Requires ===
    #
    #     Module                  Want    Have
    #     ----------------------- ---- -------
    #     ExtUtils::MakeMaker      any 7.04_01
    #     File::ShareDir::Install 0.06    0.10
    #
    # === Build Requires ===
    #
    #     Module              Want    Have
    #     ------------------- ---- -------
    #     ExtUtils::MakeMaker  any 7.04_01
    #
    # === Test Requires ===
    #
    #     Module                    Want     Have
    #     ------------------------ ----- --------
    #     CPAN::Meta::Check        0.011    0.012
    #     CPAN::Meta::Requirements 2.121    2.132
    #     ExtUtils::MakeMaker        any  7.04_01
    #     ExtUtils::Manifest        1.66     1.70
    #     File::Spec                 any     3.56
    #     Software::License::None    any 0.103010
    #     Test::FailWarnings         any    0.008
    #     Test::Fatal                any    0.014
    #     Test::File::ShareDir       any 1.001001
    #     Test::More                0.96 1.001014
    #     lib                        any     0.63
    #     utf8                       any     1.17
    #
    # === Test Recommends ===
    #
    #     Module         Want     Have
    #     ---------- -------- --------
    #     CPAN::Meta 2.120900 2.150001
    #
    # === Runtime Requires ===
    #
    #     Module                                         Want       Have
    #     ------------------------------------------ -------- ----------
    #     App::Cmd::Command::version                      any      0.330
    #     App::Cmd::Setup                               0.330      0.330
    #     App::Cmd::Tester                              0.306      0.330
    #     App::Cmd::Tester::CaptureExternal               any      0.330
    #     Archive::Tar                                    any       2.04
    #     CPAN::Meta::Converter                      2.101550   2.150001
    #     CPAN::Meta::Merge                               any   2.150001
    #     CPAN::Meta::Prereqs                        2.120630   2.150001
    #     CPAN::Meta::Requirements                      2.121      2.132
    #     CPAN::Meta::Validator                      2.101550   2.150001
    #     CPAN::Uploader                             0.103004   0.103011
    #     Carp                                            any       1.36
    #     Class::Load                                    0.17       0.23
    #     Config::INI::Reader                             any      0.025
    #     Config::MVP::Assembler                          any   2.200010
    #     Config::MVP::Assembler::WithBundles        2.200010   2.200010
    #     Config::MVP::Reader                        2.101540   2.200010
    #     Config::MVP::Reader::Findable::ByExtension      any   2.200010
    #     Config::MVP::Reader::Finder                     any   2.200010
    #     Config::MVP::Reader::INI                   2.101461   2.101463
    #     Config::MVP::Section                       2.200009   2.200010
    #     Data::Dumper                                    any      2.158
    #     Data::Section                              0.200002   0.200006
    #     DateTime                                       0.44       1.21
    #     Digest::MD5                                     any       2.54
    #     Encode                                          any       2.72
    #     ExtUtils::Manifest                             1.66       1.70
    #     File::Copy::Recursive                           any       0.38
    #     File::Find::Rule                                any       0.33
    #     File::HomeDir                                   any       1.00
    #     File::Path                                      any       2.09
    #     File::ShareDir                                  any      1.102
    #     File::ShareDir::Install                        0.03       0.10
    #     File::Spec                                      any       3.56
    #     File::Temp                                      any     0.2304
    #     File::pushd                                     any      1.009
    #     JSON::MaybeXS                                   any   1.003005
    #     List::MoreUtils                                 any      0.413
    #     List::Util                                     1.33       1.41
    #     Log::Dispatchouli                          1.102220      2.012
    #     Mixin::Linewise::Readers                      0.100      0.108
    #     Module::CoreList                                any 5.20150520
    #     Moose                                          0.92     2.1604
    #     Moose::Role                                     any     2.1604
    #     Moose::Util::TypeConstraints                    any     2.1604
    #     MooseX::LazyRequire                             any       0.11
    #     MooseX::Role::Parameterized                    1.01       1.08
    #     MooseX::SetOnce                                 any   0.200002
    #     MooseX::Types                                   any       0.46
    #     MooseX::Types::Moose                            any       0.46
    #     MooseX::Types::Path::Class                      any       0.08
    #     MooseX::Types::Perl                             any   0.101343
    #     PPI::Document                                   any      1.220
    #     Params::Util                                    any       1.07
    #     Path::Class                                    0.22       0.35
    #     Path::Tiny                                    0.052      0.076
    #     Perl::PrereqScanner                           1.016      1.023
    #     Perl::Version                                   any      1.013
    #     Pod::Eventual                              0.091480   0.094001
    #     Scalar::Util                                    any       1.41
    #     Software::License                          0.101370   0.103010
    #     Software::LicenseUtils                          any   0.103010
    #     String::Formatter                          0.100680   0.102084
    #     String::RewritePrefix                         0.005      0.007
    #     Sub::Exporter                                   any      0.987
    #     Sub::Exporter::ForMethods                       any   0.100052
    #     Sub::Exporter::Util                             any      0.987
    #     Term::Encoding                                  any       0.02
    #     Term::ReadKey                                   any       2.33
    #     Term::ReadLine                                  any       1.15
    #     Term::UI                                        any       0.46
    #     Test::Deep                                      any      0.119
    #     Text::Glob                                     0.08       0.09
    #     Text::Template                                  any       1.46
    #     Try::Tiny                                       any       0.22
    #     YAML::Tiny                                      any       1.69
    #     autodie                                         any       2.26
    #     namespace::autoclean                            any       0.28
    #     parent                                          any      0.232
    #     strict                                          any       1.09
    #     version                                         any     0.9909
    #     warnings                                        any       1.32
    #
    # === Runtime Recommends ===
    #
    #     Module                Want    Have
    #     --------------------- ---- -------
    #     Archive::Tar::Wrapper 0.15 missing
    #     Term::ReadLine::Gnu    any missing
    #
    # === Runtime Suggests ===
    #
    #     Module  Want    Have
    #     ------- ---- -------
    #     PPI::XS  any missing
    #
    t/00-report-prereqs.t ........ ok

**Comment by karenetheridge** [comment]
"Cannot determine local time zone" comes from DateTime::TimeZone::Local, via DateTime::TimeZone::<arch>.  What version do you have installed, @pink-mist and @vadz ?

**Comment by pink-mist** [comment]
$ perl -MDateTime::TimeZone::Local\ 9999 -e1
    DateTime::TimeZone::Local version 9999 required--this is only version 1.94.
    BEGIN failed--compilation aborted.

**Comment by karenetheridge** [comment]
@pink-mist one last request:  can you (with TZ unset), run:  `cpanm Devel::Confess; perl -d:Confess -Ilib t/plugins/readme.t` - thanks!

**Comment by pink-mist** [comment]
[0]suppy@celestia:~/.cpanm/work/1447789781.12384/Dist-Zilla-5.041$ perl -d:Confess -Ilib t/plugins/readme.t
    ok 1 - copyright appears in README file
    ok 2 - 'same terms as perl'-ish text appears in README
    ok 3 - dist name appears in README
    Cannot determine local time zone
     at /home/suppy/perl5/lib/perl5/DateTime/TimeZone/Local.pm line 22.
            DateTime::TimeZone::Local::TimeZone("DateTime::TimeZone::Local") called at /home/suppy/perl5/lib/perl5/DateTime/TimeZone.pm line 54
            DateTime::TimeZone::new(undef, "name", "local") called at /home/suppy/perl5/lib/perl5/x86_64-linux-thread-multi/DateTime.pm line 2036
            DateTime::set_time_zone(DateTime=HASH(0x4926e28), "local") called at /home/suppy/perl5/lib/perl5/x86_64-linux-thread-multi/DateTime.pm line 511
            DateTime::from_epoch(undef, "epoch", 1447789806, "time_zone", "local") called at /home/suppy/.cpanm/work/1447789781.12384/Dist-Zilla-5.041/lib/Dist/Zilla/Plugin/NextRelease.pm line 27
            Dist::Zilla::Plugin::NextRelease::__ANON__[/home/suppy/.cpanm/work/1447789781.12384/Dist-Zilla-5.041/lib/Dist/Zilla/Plugin/NextRelease.pm:29](Dist::Zilla::Plugin::NextRelease=HASH(0x423c588), "yyyy-MM-dd HH:mm:ssZZZZZ VVVV") called at /home/suppy/perl5/lib/perl5/String/Formatter.pm line 276
            String::Formatter::method_replace(String::Formatter=HASH(0x4222c20), ARRAY(0x423d308), Dist::Zilla::Plugin::NextRelease=HASH(0x423c588)) called at /home/suppy/perl5/lib/perl5/String/Formatter.pm line 114
            String::Formatter::format(String::Formatter=HASH(0x4222c20), "%-9v %{yyyy-MM-dd HH:mm:ssZZZZZ VVVV}d%{ (TRIAL RELEASE)}T", Dist::Zilla::Plugin::NextRelease=HASH(0x423c588)) called at /home/suppy/perl5/lib/perl5/String/Formatter.pm line 18
            String::Formatter::__ANON__[/home/suppy/perl5/lib/perl5/String/Formatter.pm:18]("%-9v %{yyyy-MM-dd HH:mm:ssZZZZZ VVVV}d%{ (TRIAL RELEASE)}T", Dist::Zilla::Plugin::NextRelease=HASH(0x423c588)) called at /home/suppy/.cpanm/work/1447789781.12384/Dist-Zilla-5.041/lib/Dist/Zilla/Plugin/NextRelease.pm line 102
            Dist::Zilla::Plugin::NextRelease::section_header(Dist::Zilla::Plugin::NextRelease=HASH(0x423c588)) called at /home/suppy/.cpanm/work/1447789781.12384/Dist-Zilla-5.041/lib/Dist/Zilla/Plugin/NextRelease.pm line 120
            Dist::Zilla::Plugin::NextRelease::munge_files(Dist::Zilla::Plugin::NextRelease=HASH(0x423c588)) called at lib/Dist/Zilla/Dist/Builder.pm line 354
            Dist::Zilla::Dist::Builder::build_in(Dist::Zilla::Tester::_Builder=HASH(0x3a22bb8), Path::Class::Dir=HASH(0x39f30c0)) called at lib/Dist/Zilla/Tester.pm line 196
            Class::MOP::Class:::around(CODE(0x2754f78), Dist::Zilla::Tester::_Builder=HASH(0x3a22bb8)) called at /home/suppy/perl5/lib/perl5/x86_64-linux-thread-multi/Class/MOP/Method/Wrapped.pm line 164
            Dist::Zilla::Tester::_Builder::_wrapped_build_in(Dist::Zilla::Tester::_Builder=HASH(0x3a22bb8)) called at /home/suppy/perl5/lib/perl5/x86_64-linux-thread-multi/Class/MOP/Method/Wrapped.pm line 95
            Dist::Zilla::Tester::_Builder::build_in(Dist::Zilla::Tester::_Builder=HASH(0x3a22bb8)) called at lib/Dist/Zilla/Dist/Builder.pm line 333
            Dist::Zilla::Dist::Builder::build(Dist::Zilla::Tester::_Builder=HASH(0x3a22bb8)) called at t/plugins/readme.t line 46
    # Tests were run but no plan was declared and done_testing() was not seen.
    # Looks like your test exited with 2 just after 3.
    [2]suppy@celestia:~/.cpanm/work/1447789781.12384/Dist-Zilla-5.041$

**Comment by rjbs** [comment]
I believe this is fixed by d7dd5d2, headed to CPAN now as 5.042.  Please let me know how it goes!

**Comment by xtaran** [comment]
I still have this issue with 5.043 on when building on Debian Unstable with Perl 5.22.1:

```
[…]
HOME=/home/abe/pkg-perl/git/packages/libdist-zilla-perl/debian/build dh_auto_test -- TEST_VERBOSE=0
        make -j1 test TEST_VERBOSE=1 TEST_VERBOSE=0
make[2]: Entering directory '/home/abe/pkg-perl/git/packages/libdist-zilla-perl'
Skip blib/lib/auto/share/module/Dist-Zilla-MintingProfile-Default/default/extra-dist.ini (unchanged)
Skip blib/lib/auto/share/module/Dist-Zilla-MintingProfile-Default/default/profile.ini (unchanged)
PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t t/commands/*.t t/diagnostics/*.t t/plugins/*.t
# 
# Versions for all modules listed in MYMETA.json (including optional ones):
# 
# === Configure Requires ===
# 
#     Module                  Want    Have
#     ----------------------- ---- -------
#     ExtUtils::MakeMaker      any 7.04_01
#     File::ShareDir::Install 0.06    0.10
# 
# === Build Requires ===
# 
#     Module              Want    Have
#     ------------------- ---- -------
#     ExtUtils::MakeMaker  any 7.04_01
# 
# === Test Requires ===
# 
#     Module                    Want     Have
#     ------------------------ ----- --------
#     CPAN::Meta::Check        0.011    0.012
#     CPAN::Meta::Requirements 2.121    2.140
#     ExtUtils::MakeMaker        any  7.04_01
#     ExtUtils::Manifest        1.66     1.70
#     File::Spec                 any     3.56
#     Software::License::None    any 0.103010
#     Test::FailWarnings         any    0.007
#     Test::Fatal                any    0.014
#     Test::File::ShareDir       any 1.001001
#     Test::More                0.96 1.001014
#     lib                        any     0.63
#     utf8                       any     1.17
# 
# === Test Recommends ===
# 
#     Module         Want     Have
#     ---------- -------- --------
#     CPAN::Meta 2.120900 2.150005
# 
# === Runtime Requires ===
# 
#     Module                                         Want       Have
#     ------------------------------------------ -------- ----------
#     App::Cmd::Command::version                      any      0.330
#     App::Cmd::Setup                               0.330      0.330
#     App::Cmd::Tester                              0.306      0.330
#     App::Cmd::Tester::CaptureExternal               any      0.330
#     Archive::Tar                                    any       2.04
#     CPAN::Meta::Converter                      2.101550   2.150005
#     CPAN::Meta::Merge                               any   2.150005
#     CPAN::Meta::Prereqs                        2.120630   2.150005
#     CPAN::Meta::Requirements                      2.121      2.140
#     CPAN::Meta::Validator                      2.101550   2.150005
#     CPAN::Uploader                             0.103004   0.103012
#     Carp                                            any       1.36
#     Class::Load                                    0.17       0.23
#     Config::INI::Reader                             any      0.025
#     Config::MVP::Assembler                          any   2.200010
#     Config::MVP::Assembler::WithBundles        2.200010   2.200010
#     Config::MVP::Reader                        2.101540   2.200010
#     Config::MVP::Reader::Findable::ByExtension      any   2.200010
#     Config::MVP::Reader::Finder                     any   2.200010
#     Config::MVP::Reader::INI                   2.101461   2.101463
#     Config::MVP::Section                       2.200009   2.200010
#     Data::Dumper                                    any      2.158
#     Data::Section                              0.200002   0.200006
#     DateTime                                       0.44       1.21
#     Digest::MD5                                     any       2.54
#     Encode                                          any       2.72
#     ExtUtils::Manifest                             1.66       1.70
#     File::Copy::Recursive                           any       0.38
#     File::Find::Rule                                any       0.34
#     File::HomeDir                                   any       1.00
#     File::Path                                      any       2.09
#     File::ShareDir                                  any      1.102
#     File::ShareDir::Install                        0.03       0.10
#     File::Spec                                      any       3.56
#     File::Temp                                      any     0.2304
#     File::pushd                                     any      1.009
#     JSON::MaybeXS                                   any   1.003005
#     List::MoreUtils                                 any      0.413
#     List::Util                                     1.33       1.42
#     Log::Dispatchouli                          1.102220      2.012
#     Mixin::Linewise::Readers                      0.100      0.108
#     Module::CoreList                                any 5.20160120
#     Moose                                          0.92     2.1604
#     Moose::Role                                     any     2.1604
#     Moose::Util::TypeConstraints                    any     2.1604
#     MooseX::LazyRequire                             any       0.11
#     MooseX::Role::Parameterized                    1.01       1.08
#     MooseX::SetOnce                                 any   0.200002
#     MooseX::Types                                   any       0.46
#     MooseX::Types::Moose                            any       0.46
#     MooseX::Types::Path::Class                      any       0.08
#     MooseX::Types::Perl                             any   0.101343
#     PPI::Document                                   any      1.220
#     Params::Util                                    any       1.07
#     Path::Class                                    0.22       0.35
#     Path::Tiny                                    0.052      0.076
#     Perl::PrereqScanner                           1.016      1.023
#     Perl::Version                                   any      1.013
#     Pod::Eventual                              0.091480   0.094001
#     Scalar::Util                                    any       1.42
#     Software::License                          0.101370   0.103010
#     Software::LicenseUtils                          any   0.103010
#     String::Formatter                          0.100680   0.102084
#     String::RewritePrefix                         0.005      0.007
#     Sub::Exporter                                   any      0.986
#     Sub::Exporter::ForMethods                       any   0.100052
#     Sub::Exporter::Util                             any      0.986
#     Term::Encoding                                  any       0.02
#     Term::ReadKey                                   any       2.33
#     Term::ReadLine                                  any       1.15
#     Term::UI                                        any       0.46
#     Test::Deep                                      any      1.120
#     Text::Glob                                     0.08       0.09
#     Text::Template                                  any       1.46
#     Try::Tiny                                       any       0.24
#     YAML::Tiny                                      any       1.69
#     autodie                                         any       2.29
#     namespace::autoclean                            any       0.28
#     parent                                          any      0.232
#     strict                                          any       1.09
#     version                                         any     0.9912
#     warnings                                        any       1.34
# 
# === Runtime Recommends ===
# 
#     Module                Want Have
#     --------------------- ---- ----
#     Archive::Tar::Wrapper 0.15 0.23
#     Term::ReadLine::Gnu    any 1.28
# 
# === Runtime Suggests ===
# 
#     Module  Want    Have
#     ------- ---- -------
#     PPI::XS  any missing
# 
t/00-report-prereqs.t ........ ok
t/commands/authordeps.t ...... ok
t/commands/listdeps.t ........ ok
t/compile.t .................. ok
t/diagnostics/main-module.t .. ok
t/diagnostics/plugin-fail.t .. ok
t/empty-abstract.t ........... ok
t/file-addedby.t ............. ok
t/file.t ..................... ok
t/load_config.t .............. ok
t/minter.t ................... ok
t/plugins/autolicense.t ...... ok
t/plugins/autoname.t ......... ok
t/plugins/autoprereqs.t ...... ok
t/plugins/autoversion.t ...... ok
t/plugins/confirmrelease.t ... ok
t/plugins/distmeta-merge.t ... ok
Cannot determine local time zone
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 2 just after 6.
t/plugins/distmeta.t ......... 
Dubious, test returned 2 (wstat 512, 0x200)
All 6 subtests passed 
t/plugins/encoding.t ......... ok
t/plugins/extratests.t ....... ok
t/plugins/fakerelease.t ...... ok
t/plugins/ffbyname.t ......... ok
t/plugins/filefinders.t ...... ok
t/plugins/filter-b.t ......... ok
t/plugins/gatherdir.t ........ ok
t/plugins/generatefile.t ..... ok
t/plugins/installdirs.t ...... ok
Cannot determine local time zone
    # Child (non-ASCII author) exited without calling finalize()

#   Failed test 'non-ASCII author'
#   at /usr/share/perl5/Test/Builder.pm line 279.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 2 just after 2.
t/plugins/license.t .......... 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 1/2 subtests 
t/plugins/makemaker.t ........ ok
t/plugins/manifest.t ......... ok
t/plugins/metanoindex.t ...... ok
t/plugins/metaresources.t .... ok
t/plugins/misctests.t ........ ok
t/plugins/modulebuild.t ...... ok
t/plugins/nextrelease.t ...... ok
t/plugins/pkgdist.t .......... ok
t/plugins/pkgversion.t ....... ok
t/plugins/podsyntaxtests.t ... ok
t/plugins/podversion.t ....... ok
t/plugins/prereqs.t .......... ok
t/plugins/prunes.t ........... ok
Cannot determine local time zone
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 2 just after 3.
t/plugins/readme.t ........... 
Dubious, test returned 2 (wstat 512, 0x200)
All 3 subtests passed 
t/plugins/release_status.t ... ok
t/plugins/testrelease.t ...... ok
t/plugins/uploadtocpan.t ..... ok
t/tester-demo.t .............. ok
t/tester-sort.t .............. ok
t/tester.t ................... ok
t/util.t ..................... ok
t/zzz-check-breaks.t ......... ok

Test Summary Report
-------------------
t/plugins/distmeta.t       (Wstat: 512 Tests: 6 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
t/plugins/license.t        (Wstat: 512 Tests: 2 Failed: 1)
  Failed test:  2
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
t/plugins/readme.t         (Wstat: 512 Tests: 3 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
Files=50, Tests=455, 200 wallclock secs ( 0.29 usr  0.40 sys + 81.70 cusr  9.99 csys = 92.38 CPU)
Result: FAIL
Failed 3/50 test programs. 1/455 subtests failed.
Makefile:1851: recipe for target 'test_dynamic' failed
[…]
```

**Comment by xtaran** [comment]
Setting TZ=UTC in the environment before running the test suite fixes it for me. Seems to have been unset before (or set to the empty string).

**Comment by karenetheridge** [comment]
@xtaran As from the previous investigation: "Cannot determine local time zone" comes from DateTime::TimeZone::Local, via DateTime::TimeZone::<arch>. What versions of these do you have installed?

(@rjbs I'd add reporting of these modules to t/00-report-prereqs.t, and possibly add a MSWin32-specific prereq to ensure these modules get updated appropriately.)

**Comment by xtaran** [comment]
Hi Karen,

On Thu, Jan 21, 2016 at 01:27:48PM -0800, Karen Etheridge wrote:
> @xtaran As from the previous investigation: "Cannot determine local
> time zone" comes from DateTime::TimeZone::Local, via
> DateTime::TimeZone::<arch>. What versions of these do you have
> installed?

Not sure which <arch> is used in the end:

```
→ pmvers DateTime::TimeZone::Local
1.94
→ pmvers DateTime::TimeZone::Local::Unix
1.94
→ pmvers DateTime::TimeZone::Tzfile
0.010
→ pmvers DateTime::TimeZone::SystemV
0.009
→ pmvers DateTime::TimeZone::UTC
1.94
→ pmvers DateTime::TimeZone::Catalog
1.94
→ pmvers DateTime::TimeZone::Floating
1.94
→ pmvers DateTime::TimeZone::OlsonDB
1.94
→ pmvers DateTime::TimeZone::OffsetOnly
1.94
```
		Kind regards, Axel
